export const categories = [
  { id: "all", label: "All services", icon: "grid" },
  { id: "equipment", label: "Equipment", icon: "tractor" },
  { id: "labour", label: "Farm labour", icon: "users" },
  { id: "irrigation", label: "Irrigation", icon: "droplets" },
  { id: "advisory", label: "Expert help", icon: "sprout" },
];

export const services = [
  {
    id: "tractor-tilling",
    category: "equipment",
    name: "Tractor & tilling",
    shortName: "Tractor",
    provider: "Kaveri Farm Machines",
    rating: 4.9,
    reviews: 128,
    distance: "3.2 km",
    price: 1200,
    unit: "acre",
    icon: "tractor",
    tone: "sun",
    duration: "1–2 hours / acre",
    description:
      "Get your field ready with a verified operator and a maintained 45 HP tractor. Fuel, operator, and standard tilling tools are included.",
    includes: ["Verified local operator", "Fuel included", "Rotavator or cultivator", "On-time arrival updates"],
  },
  {
    id: "harvest-crew",
    category: "labour",
    name: "Harvest support crew",
    shortName: "Harvest crew",
    provider: "GreenHands Collective",
    rating: 4.8,
    reviews: 86,
    distance: "5.6 km",
    price: 850,
    unit: "worker/day",
    icon: "users",
    tone: "clay",
    duration: "8-hour shift",
    description:
      "Book an experienced local crew for harvesting, sorting, and field loading with a clear daily rate.",
    includes: ["Experienced farm workers", "Flexible crew size", "Basic hand tools", "Attendance confirmation"],
  },
  {
    id: "crop-spraying",
    category: "equipment",
    name: "Precision crop spraying",
    shortName: "Crop spraying",
    provider: "Sahya Crop Care",
    rating: 4.7,
    reviews: 64,
    distance: "7.1 km",
    price: 680,
    unit: "acre",
    icon: "wind",
    tone: "mint",
    duration: "45–60 min / acre",
    description:
      "Uniform spraying by a trained operator using calibrated equipment. Chemical cost is shown separately before confirmation.",
    includes: ["Calibrated sprayer", "Safety equipment", "Weather check", "Coverage confirmation"],
  },
  {
    id: "irrigation-repair",
    category: "irrigation",
    name: "Irrigation repair",
    shortName: "Irrigation",
    provider: "NeerFlow Services",
    rating: 4.9,
    reviews: 103,
    distance: "2.4 km",
    price: 499,
    unit: "visit",
    icon: "droplets",
    tone: "water",
    duration: "60–90 minutes",
    description:
      "A technician will inspect pumps, pipes, and drip lines, explain the issue, and provide a repair estimate before starting work.",
    includes: ["Complete inspection", "Upfront repair estimate", "Basic leak sealing", "7-day service support"],
  },
  {
    id: "soil-testing",
    category: "advisory",
    name: "Soil health testing",
    shortName: "Soil testing",
    provider: "Mitti Health Lab",
    rating: 4.8,
    reviews: 51,
    distance: "9.8 km",
    price: 750,
    unit: "sample",
    icon: "flask",
    tone: "soil",
    duration: "Report in 3 days",
    description:
      "Field sample collection with a plain-language soil health report covering pH, major nutrients, and crop-specific recommendations.",
    includes: ["Sample collection", "NPK and pH analysis", "Digital report", "15-minute expert call"],
  },
  {
    id: "farm-transport",
    category: "equipment",
    name: "Produce transport",
    shortName: "Transport",
    provider: "GramRoute Logistics",
    rating: 4.6,
    reviews: 92,
    distance: "4.5 km",
    price: 32,
    unit: "km",
    icon: "truck",
    tone: "gold",
    duration: "Same-day pickup",
    description:
      "Book a clean mini-truck for produce transport with transparent distance pricing and live driver updates.",
    includes: ["Verified driver", "Loading ropes and cover", "Live trip status", "Digital delivery receipt"],
  },
];

export const demoBookings = [
  {
    id: "AGR-2048",
    serviceId: "irrigation-repair",
    status: "In progress",
    date: "Today",
    time: "10:30 AM",
    location: "North field, Thiruvallur",
    provider: "Ravi Kumar",
    amount: 589,
    progress: 2,
  },
  {
    id: "AGR-1986",
    serviceId: "soil-testing",
    status: "Completed",
    date: "12 Aug",
    time: "9:00 AM",
    location: "Main farm, Thiruvallur",
    provider: "Mitti Health Lab",
    amount: 750,
    progress: 4,
  },
];

export const notifications = [
  {
    id: 1,
    title: "Ravi is on the way",
    body: "Your irrigation technician will arrive in about 18 minutes.",
    time: "8 min ago",
    type: "route",
    unread: true,
  },
  {
    id: 2,
    title: "Booking confirmed",
    body: "Tractor & tilling is confirmed for Saturday at 8:00 AM.",
    time: "Yesterday",
    type: "check",
    unread: true,
  },
  {
    id: 3,
    title: "Weather reminder",
    body: "Light rain is expected tomorrow evening. Your morning booking is unaffected.",
    time: "Yesterday",
    type: "weather",
    unread: false,
  },
];

export const onboardingSlides = [
  {
    eyebrow: "Trusted farm support",
    title: "The right service, right when your field needs it.",
    copy: "Find verified equipment and skilled workers near your farm—without calling multiple middlemen.",
  },
  {
    eyebrow: "Clear prices",
    title: "Know the full cost before you book.",
    copy: "Compare providers, see what is included, and choose a payment method that works for you.",
  },
  {
    eyebrow: "Updates you can trust",
    title: "Follow every job from confirmation to completion.",
    copy: "Get simple arrival updates, contact your provider, and keep a digital service record.",
  },
];
